### ISSUE TITLE
Our Christmas wishlist

### ISSUE THREAD

**Issue by serega6531** [flawwan/CTF-Writeups#1]
"The file also has to be 2000 bytes or else the upload refused to unzip the file."
I don't think this is correct. I uploaded any zip with <2000 bytes files and it worked great.

**Comment by flawwan** [comment]
Hmm yea I'm not entirely sure about this part. When I tried to upload zip containing a file with size < 2000 bytes it said something along the lines:
"detected ultra light file, refuse to unzip". Don't remember exactly but it refused to unzip.. 

I solved it by just padding it to 2000 bytes.

Filesize greater than 2000 bytes was also prohibited.

Anyways, I'll add a note in the writeup when I get to a computer. Thanks for pointing it out:)
