### ISSUE TITLE
Please explain this 

### ISSUE THREAD

**Issue by Shrimant12** [flawwan/CTF-Writeups#2]
Opening all the images in photoshop using the Place command to import all images as new layers.

**Comment by flawwan** [comment]
1. File > Place
2. Select the file you want to place
3. Click Place.

This will add the image as a new layer to the current document. Very useful for this challenge as it's important to be able to move individual images.

You can read more about the place command here: https://helpx.adobe.com/photoshop/using/placing-files.html.

Hope that clears it up for you.

**Comment by Shrimant12** [comment]
Yes, thank you. You participate in CTFs alone or you have a team ?

**Comment by flawwan** [comment]
Playing in team with my buddies from school!
