### ISSUE TITLE
How does sqlmap get information when none is returned -- DAS BLOG 2

### ISSUE THREAD

**Issue by UlisseMini** [flawwan/CTF-Writeups#3]
How can sqlmap get the databases and tables when the query result is not returned?

**Comment by flawwan** [comment]
Hi! Sorry but I don't understand what you mean?

Neverlan shutdown the servers because the CTF ended. You can't follow the "writeup" if you want to get the same result. You'll have to ask the admins for the source of das blog 2.

**Comment by UlisseMini** [comment]
Nevermind, my question was because if you do `'SHOW TABLES;#` (valid sqli) it will not give you the result, i ran sqlmap and the query it used was some monster query that created a new user with the name equal to the base64 (i think) of the database then logged into it (i'm highly guessing) anyways i solved this challange with `OR 1=FLOOR(RAND()*2);#` then spammed that until i got into the admin account :P

a better way would have been ```'OR 1=1 LIMIT 1,1``` then change 1,1 to iterate through the table
